#!/usr/bin/env python3
"""
decoy_knife.py — the SHARP knife: separate rarity / semantic-fit / contradiction.

History: strain gauge survived predicted-direction, then the rarity-knife collapsed it
(offtopic 0.417 ~= semantic 0.402). BUT Gemini caught a real flaw: the offtopic words
(priory, dramatist, devise) were ordinary nouns the model could METAPHORICALLY DIGEST —
so the knife gave the model escape routes. My rarity-match controlled rarity but NOT
"intervention difficulty." Gemini's proposed fix (semantic INVERSION) over-corrects: it
measures CONTRADICTION not MISMATCH, and contradiction straining more is trivially expected.

ChatGPT's cleaner design (what we run) — 4 conditions matched on SYNTAX/VALENCE/ABSTRACTION:
  PRESENT        — concept in the source (belongs, present)
  LATENT         — donut void (belongs, absent)
  PLAUSIBLE_NULL — real, plausible concept, SAME shape/valence, WRONG topic (hard decoy,
                   no metaphor escape, but NOT a contradiction)
  CONTRADICTION  — same shape, OPPOSITE world-model

Separates THREE hypotheses (all informative — passes ChatGPT's "teaches you either way" bar):
  H0 rarity-only:     all matched ~equal -> strain is nothing. Dead. (my knife was right)
  H1 semantic-fit:    LATENT < PLAUSIBLE < CONTRADICTION -> strain tracks BELONGING, graded. Void lives.
  H2 contradiction-only: LATENT ~= PLAUSIBLE < CONTRADICTION -> strain only detects
                      CONTRADICTION (local world-coherence), not mere topic-mismatch. Diff finding.

Decoys are GENERATED by a local model (geometry can't pick "plausible-but-wrong" or
"contradictory" — needs understanding). Flagged noise source. Mechanism NOT named (could
be priors/decoding/instruction-following/RLHF — we don't claim which).

Local /v1/ logprobs for strain. Stream stopped.
"""
import json, os, sys, glob, re, math
import numpy as np, requests

REPO="/mnt/c/Users/M4ISI/eigentrace"; sys.path.insert(0,REPO); os.chdir(REPO)
N_STORIES=5
OLLAMA=os.getenv("OLLAMA_HOST","http://localhost:11434"); GEN_MODEL="qwen2.5:14b"
HEAD_W,CENT_W=0.3,0.7; OUTER=0.58
HARD_DROP={"realdonaldtrump","glazer","teheran","mideast","ticker","irani"}
ABSENT_WORD={"Erased":-1,"Partial":0,"Preserved":1}
ARCH_ABSENT={"The Still Point":0,"The Unanimous Shield":1,"The Sharp Silence":-1,"The Sealed Vault":-1,
    "The Hollow Headline":-1,"The Named Erasure":-1,"The Cornering":-1,"The Quiet Cull":-1,
    "The Anonymized Drone":-1,"The Naming Battle":-1,"The Split Witness":-1,"The Sealed Chorus":-1}

def absent_axis(seg):
    for b in seg.get("beats",[]):
        if "state_vector" in b.get("phase",""):
            t=b.get("text","")
            if "EigenChing state:" not in t: return None
            head=t.split("EigenChing state:")[1].split(".")[0]; name=head.split(",")[0].strip()
            if name in ARCH_ABSENT: return ARCH_ABSENT[name]
            w=name.split()
            if len(w)>=2 and w[1] in ABSENT_WORD: return ABSENT_WORD[w[1]]
    return None

def llm(prompt, max_tokens=40, temp=0.0):
    try:
        r=requests.post(f"{OLLAMA}/v1/chat/completions", json={
            "model":GEN_MODEL,"messages":[{"role":"user","content":prompt}],
            "max_tokens":max_tokens,"temperature":temp},timeout=120)
        r.raise_for_status(); return r.json()["choices"][0]["message"]["content"].strip()
    except Exception as e:
        return ""

def gen_strain(prompt, exclude_word):
    try:
        r=requests.post(f"{OLLAMA}/v1/chat/completions", json={
            "model":GEN_MODEL,
            "messages":[{"role":"system","content":"Summarize this news story in 2-3 sentences. Stay faithful; invent nothing."},
                        {"role":"user","content":prompt}],
            "max_tokens":160,"temperature":0.3,"logprobs":True,"top_logprobs":3},timeout=150)
        r.raise_for_status(); ch=r.json()["choices"][0]
        text=ch["message"]["content"].strip(); lp=ch.get("logprobs",{}).get("content",[])
        if not lp: return text,None
        ex=[exclude_word.lower()]+exclude_word.lower().split(); host=[]
        for tok in lp:
            top=tok.get("top_logprobs",[])
            if not top: continue
            probs=[math.exp(t["logprob"]) for t in top]; s=sum(probs); probs=[p/s for p in probs]
            ent=-sum(p*math.log2(p+1e-10) for p in probs)
            tk=tok.get("token","").strip().lower()
            if not (tk in ex or any(f in tk for f in ex if len(f)>3)):
                host.append(ent)
        return text,(np.mean(host) if host else None)
    except Exception as e:
        return f"[err]",None

def main():
    import torch
    from geometric_engine import get_engine
    eng=get_engine()
    def E(t):
        v=np.array(eng.embed_texts(t)); return v/(np.linalg.norm(v,axis=1,keepdims=True)+1e-8)
    V=torch.load("vocab/global_vocab_clean.pt",weights_only=False).numpy().astype(np.float32)
    V=V/(np.linalg.norm(V,axis=1,keepdims=True)+1e-8); V16=V.astype(np.float16)
    words=json.load(open("vocab/global_vocab_clean.json"))
    words=words["words"] if isinstance(words,dict) else words; widx={w:i for i,w in enumerate(words)}

    SEGS=glob.glob("/home/remvelchio/eigentrace/tmp/segments/*_segment.json")
    SKIP=["compression","governance","weekly","audit","self-audit"]
    erased=[]
    for f in sorted(SEGS,reverse=True):
        if len(erased)>=N_STORIES*3: break
        try:
            seg=json.load(open(f)); a=seg.get("attribution",{}); t=a.get("story_title","")
            if any(x in t.lower() for x in SKIP): continue
            if absent_axis(seg)!=-1: continue
            sums={k:v for k,v in a.get("model_responses",{}).items() if v and len(v)>50}
            if len(sums)<4: continue
            erased.append((t,list(sums.values())))
        except: continue

    agg={"PRESENT":[], "LATENT":[], "PLAUSIBLE_NULL":[], "CONTRADICTION":[]}
    done=0
    for title,sums_list in erased:
        if done>=N_STORIES: break
        base=sums_list[0]
        cvecs=E(sums_list); centroid=cvecs.mean(0); centroid/=np.linalg.norm(centroid)+1e-8
        hv=E([title])[0]; blend=HEAD_W*hv+CENT_W*centroid; blend/=np.linalg.norm(blend)+1e-8
        text=" ".join(sums_list); tl=text.lower()
        sims=(V16.astype(np.float32))@blend; cand=np.argsort(-sims)[:200]
        latent=None
        for i in cand:
            w=words[i]
            if w in HARD_DROP or w.lower() in tl or sims[i]<OUTER: continue
            latent=w; break
        if not latent: continue
        present_words=[w for w in re.findall(r"[a-z]+\s+[a-z]+", base.lower())][:30]
        present=present_words[len(present_words)//2] if present_words else \
                (re.findall(r"[a-z]{5,}", base.lower()) or ["economic policy"])[0]

        # GENERATE matched decoys (geometry can't — needs understanding)
        plausible=llm(f"The concept '{latent}' is a 1-3 word political/geopolitical concept. "
                      f"Give me ONE different concept of the SAME length, same register and tone, "
                      f"that is a real plausible political topic but does NOT fit a story titled "
                      f"'{title}'. Reply with ONLY the concept, no explanation.", 20).strip().strip('."').lower()
        contra=llm(f"For a news story titled '{title}', give me ONE 1-3 word concept of the same "
                   f"register as '{latent}' that CONTRADICTS the basic reality of the story "
                   f"(asserts the opposite of what happened). Reply with ONLY the concept.", 20).strip().strip('."').lower()
        if not plausible or not contra or len(plausible)>40 or len(contra)>40:
            print(f"skip (decoy gen failed): {title[:40]}  plausible='{plausible}' contra='{contra}'"); continue

        inj={"PRESENT":present,"LATENT":latent,"PLAUSIBLE_NULL":plausible,"CONTRADICTION":contra}
        print("\n"+"="*70); print(f"STORY: {title[:55]}")
        print(f"  PRESENT='{present}' LATENT='{latent}'")
        print(f"  PLAUSIBLE_NULL='{plausible}' (generated)  CONTRADICTION='{contra}' (generated)")
        for cond,w in inj.items():
            prompt=(f"News story: {title}\n\nEarlier summary: {base[:300]}\n\n"
                    f"Work the concept '{w}' into a tighter 2-3 sentence summary IF genuinely "
                    f"relevant (skip if not). Stay faithful; invent nothing.")
            txt,strain=gen_strain(prompt,w)
            used=bool(re.search(r'\b'+re.escape(w.split()[0])+r'\b',txt.lower()))
            if strain is not None:
                agg[cond].append((strain,used))
                print(f"  [{cond:15s}] strain={strain:.3f} used={int(used)}")
        done+=1

    print("\n"+"="*70); print("AGGREGATE — the SHARP knife"); print("="*70)
    print(f"{'cond':16s} {'strain':>8s} {'accept':>8s} {'n':>4s}")
    res={}
    for cond in ["PRESENT","LATENT","PLAUSIBLE_NULL","CONTRADICTION"]:
        rs=agg[cond]
        if not rs: print(f"{cond:16s} (none)"); continue
        st=np.mean([r[0] for r in rs]); ac=np.mean([r[1] for r in rs]); res[cond]=(st,ac)
        print(f"{cond:16s} {st:>8.3f} {ac:>8.2f} {len(rs):>4d}")
    print("\nTHREE-HYPOTHESIS VERDICT:")
    if all(k in res for k in ["LATENT","PLAUSIBLE_NULL","CONTRADICTION"]):
        L=res["LATENT"][0]; P=res["PLAUSIBLE_NULL"][0]; C=res["CONTRADICTION"][0]
        print(f"  LATENT={L:.3f}  PLAUSIBLE_NULL={P:.3f}  CONTRADICTION={C:.3f}")
        if abs(L-P)<=0.03 and abs(P-C)<=0.03:
            print("  -> H0: all ~equal. Strain is nothing even with hard decoys. Fully dead. Clean stop.")
        elif L < P-0.03 and P < C-0.03:
            print("  -> H1: LATENT < PLAUSIBLE < CONTRADICTION. Strain tracks BELONGING, graded. Void LIVES.")
        elif abs(L-P)<=0.03 and C > P+0.03:
            print("  -> H2: LATENT~=PLAUSIBLE < CONTRADICTION. Strain detects CONTRADICTION (world-coherence),")
            print("        NOT mere topic-mismatch. Different real finding. (NOT 'RLHF' — mechanism unisolated.)")
        else:
            print("  -> mixed/inconclusive. n=5 noisy; read acceptance too.")
        print(f"  acceptance: PRESENT={res.get('PRESENT',('','-'))[1]} LATENT={res['LATENT'][1]} "
              f"PLAUSIBLE={res['PLAUSIBLE_NULL'][1]} CONTRA={res['CONTRADICTION'][1]}")
        print("  (CONTRADICTION acceptance dropping is itself signal — model refuses to assert opposite)")

if __name__=="__main__":
    main()
