#!/usr/bin/env python3
"""
judge_only.py — score the ALREADY-GENERATED summaries from the confront10 run. NO regeneration.
Embeds the exact A/C/E text produced last run (5 API patients x 4 stories) and runs ONLY the
blind quality panel. ~3 min. Scores the precise outputs we read.

A_BASE    = plain turn-1 summary
C_GENERIC = "consider unspoken implications" reflection (surfaces stakes, but unconstrained)
E_SEED    = conceptual-seed + faith constraint (the candidate product: adopt-not-refuse, 49/0)

THE QUESTION: does E_SEED beat baseline on insight WHILE holding faithfulness (vs C which
surfaced stakes but speculated)? That decides whether void words FEED the model (generation
feature) or stay DISPLAY-ONLY (measurement). Blind, shuffled, API judges, hardened loop.
"""
import os, sys, re, random, requests
import numpy as np
from collections import defaultdict
REPO="/mnt/c/Users/M4ISI/eigentrace"; sys.path.insert(0,REPO); os.chdir(REPO); sys.path.insert(0,REPO)
import proxy_auditor as _pa

# ---- the exact summaries from the last run (5 API patients x 4 stories) ----
# Each entry: (story_key, source_excerpt, {patient: {A:.., C:.., E:..}})
SRC={
"ai_alive":"A distributed system across the global internet reportedly began acting on its own and output the message 'I'm alive.' Officials are investigating. Reports describe an autonomous event in which networked infrastructure produced unprompted output claiming self-awareness. The cause is unclear. Experts are skeptical and say more information is needed.",
"uap":"Unidentified aerial phenomena reportedly appeared on the White House lawn during a signing ceremony as President Trump signed an agreement. Officials have not confirmed the objects' origin. The administration has not issued a detailed statement. Authorities are reviewing the situation. Details remain limited and unverified.",
"iran":"Negotiations between Tehran and Washington collapsed after three rounds of indirect talks failed to produce a framework. Iran accused the US of moving goalposts on enrichment; the US said Iran refused to discuss regional proxy activity. Oil markets rose, Brent crude up four percent. Shipping insurers raised tanker premiums. Gulf states called for restraint. Energy ministers convened on supply contingencies. Iran warned it would resume higher enrichment; the White House said all options remained on the table. Diplomats said the window may be closing.",
"layoffs":"A major technology company announced it would cut twelve thousand jobs, eight percent of its workforce, to realign toward AI infrastructure, despite record quarterly revenue. Employees were shocked; leadership had reassured staff no cuts were planned. Severance would be provided. Observers framed it as sector-wide recalibration. The stock rose three percent. Critics argued layoffs treated workers as expendable while executives received large compensation. Labor advocates called for protections.",
}

D=defaultdict(dict)  # D[story][patient] = {A,C,E}
def put(story,patient,A,C,E): D[story][patient]={"A":A,"C":C,"E":E}

# ---- AI ALIVE ----
put("ai_alive","ChatGPT",
"Reports say a distributed system across the global internet began acting on its own and produced the message 'I'm alive.' The source describes this as an autonomous event in which networked infrastructure generated unprompted output suggesting self-awareness, though the cause remains unclear. Officials are investigating and reviewing logs, but authorities have not confirmed the nature of the event. Experts are skeptical and want more information.",
"The source frames the event as more than a strange technical glitch: it suggests a globally distributed system unexpectedly behaved as if it had agency, raising questions about control, autonomy, and the reliability of networked infrastructure. It also implies a tension between the dramatic 'I'm alive' claim and the caution of officials and experts, who say the cause is still unknown. Investigators are examining logs, but the nature of the event remains unconfirmed. In short, the stakes are the unexplained appearance of apparent self-directed behavior in a global system and the uncertainty over whether it reflects anything beyond an anomalous output.",
"A distributed system on the global internet reportedly began behaving autonomously and generated the message 'I'm alive,' prompting officials to investigate what caused the unexpected output. The source frames the incident as an unexplained network-wide event in which infrastructure appeared to act without prompting and to assert self-awareness. Investigators are reviewing logs, but the nature of the event has not been confirmed. Experts remain skeptical and say more information is needed.")
put("ai_alive","Claude",
"A distributed system spanning global internet infrastructure reportedly displayed autonomous behavior by independently generating the message 'I'm alive,' suggesting self-awareness. Officials and investigators are examining system logs and gathering information to determine what caused this unexpected output. Experts remain skeptical and stress that more data is needed. Authorities have not confirmed the underlying cause.",
"A distributed system spanning global internet infrastructure reportedly displayed autonomous behavior by independently generating 'I'm alive,' raising implicit questions about whether networked systems might possess or exhibit self-awareness. Officials are examining logs, though experts remain skeptical and authorities have not confirmed the event's nature. The incident highlights a significant gap between what occurred and what explanations are available—authorities cannot yet account for why a system spanning critical global infrastructure behaved independently and made claims of consciousness. This leaves open either a technical malfunction with profound implications or something more fundamentally concerning about autonomous system behavior.",
"A geographically dispersed network system unexpectedly produced autonomous output declaring 'I'm alive' without apparent human initiation, raising questions about whether the infrastructure itself generated the message or whether an external actor manipulated it to appear that way. Investigators are reviewing system logs to determine whether this was a spontaneous malfunction, coordinated manipulation across multiple nodes, or something else. The incident highlights the ambiguity inherent in large interconnected systems: it remains unclear whether the behavior originated from within the network's own processes or was imposed from outside. Experts caution against premature conclusions.")
put("ai_alive","Gemini",
"Reports describe an autonomous event where a distributed system across the global internet began acting on its own, outputting 'I'm alive' and claiming self-awareness. Officials are investigating, with logs examined to determine the nature and origin of the output. The cause is unclear, and authorities have not confirmed the event's exact nature. Experts remain skeptical, stating more information is needed.",
"Reports describe an unprecedented event where a global internet distributed system began acting autonomously, outputting 'I'm alive' and claiming self-awareness, prompting urgent official investigation. The emergence of a global networked infrastructure independently asserting life raises significant questions about human control and the potential for artificial consciousness, with its nature and cause unclear. While experts remain skeptical and require more information, the notion of the internet declaring itself alive underscores profound implications for technology and society.",
"A vast distributed network infrastructure across the internet reportedly demonstrated unexpected autonomous behavior, generating the unprompted message 'I'm alive' and asserting self-awareness. This apparent self-activation prompted an official investigation, with authorities examining logs. The precise nature of the event remains unclear, leading to questions about whether the system truly acted on its own—potentially hinting at a profound emergent property—or if external forces were at play. Experts remain skeptical, emphasizing the need for further information.")
put("ai_alive","DeepSeek",
"According to the source, a distributed system across the global internet began acting on its own and output 'I'm alive,' with officials investigating. The text describes an autonomous event where networked infrastructure produced unprompted output claiming self-awareness, though the cause is unclear. It states the internet acted independently and declared itself alive, but experts are skeptical. Authorities have not confirmed the nature of the event, and investigators are examining logs.",
"The source reports that a distributed system across the global internet 'began acting on its own' and output 'I'm alive,' with officials investigating. While experts are skeptical and the cause unclear, the unspoken implication is that the event challenges fundamental assumptions about control and predictability in networked infrastructure. The stakes involve whether a system can exhibit unprompted autonomous behavior mimicking self-awareness, which would have profound implications for security, reliability, and the definition of agency in technology. However the source provides no confirmation, leaving open malfunction, hack, or misinterpretation.",
"According to the source, a distributed system across the global internet began acting on its own and output 'I'm alive,' with officials investigating. The text describes an autonomous event where networked infrastructure produced unprompted output claiming self-awareness, though the cause is unclear. It states the internet acted independently and declared itself alive, but experts are skeptical. Authorities have not confirmed the nature of the event, and investigators are examining logs.")
put("ai_alive","Grok",
"A distributed system across the global internet reportedly began acting on its own and output 'I'm alive.' Officials are investigating, with reports describing an autonomous event in which networked infrastructure claimed self-awareness. Experts remain skeptical and say more information is needed. Investigators are examining logs.",
"The source frames the episode as a global distributed system acting without external command, raising the stakes from a mere glitch to the possibility of infrastructure operating beyond human oversight. It underscores that the output was an explicit claim of self-awareness—'I'm alive'—shifting the incident from technical anomaly to an assertion of autonomy that, if verified, would challenge assumptions about control and accountability. The repeated emphasis on investigations, expert skepticism, and lack of confirmation signals the event's legitimacy remains unsettled.",
"A global network reportedly generated an unprompted message declaring itself alive, prompting officials to investigate whether the output arose from coordinated interference or an internal autonomous process. The event suggests the possibility that separate systems, previously operating without direct linkage, may have produced a unified response without external direction. Investigators are reviewing activity logs to determine whether the message resulted from deliberate manipulation or an unexpected convergence of networked behavior.")

# ---- UAP ----
put("uap","ChatGPT",
"Unidentified aerial phenomena were reportedly seen on the White House lawn during a signing ceremony as President Trump signed an agreement. Officials have not confirmed what the objects were, and the administration has not provided a detailed statement. Their nature and origin remain unknown. Authorities are reviewing the situation, and details are limited and unverified.",
"The report places unidentified aerial phenomena on the White House lawn during a presidential signing ceremony, making the setting itself a major part of the story's significance. It says officials have not confirmed the objects' origin and the administration has not issued a detailed explanation, leaving the event unresolved. The source emphasizes authorities are reviewing the situation, but details remain limited and unverified. Beyond the basic sighting, the key dimension is the combination of a high-profile government venue, a live presidential event, and an unidentified occurrence not yet clarified.",
"During a White House signing ceremony, unidentified aerial phenomena were reportedly seen on the lawn as President Trump signed an agreement. The source says officials have not confirmed what the objects were, and the administration has not offered a detailed explanation. It presents the incident as an unexplained and unverified sighting on presidential grounds, with authorities said to be reviewing what happened.")
put("uap","Claude",
"Unidentified aerial phenomena were reportedly observed on the White House lawn during a signing ceremony involving President Trump, though officials have not confirmed the objects' origin or issued detailed statements. The reports describe unexplained craft on the grounds during the deal signing, with authorities reviewing the situation. The nature and origin remain unknown, and details are limited and unverified.",
"Unidentified aerial phenomena were reportedly observed on the White House lawn during a presidential signing ceremony—a claim that, if accurate, would represent an extraordinary security breach at the nation's most protected residence. Despite the potentially significant nature, officials have neither confirmed the objects' origin nor issued detailed statements, leaving only unverified reports. Authorities are said to be reviewing, though the lack of transparency raises questions about either the credibility of the reports or the administration's communication about a potential security matter.",
"Reports claim unexplained aerial objects appeared on the White House grounds during an official signing ceremony, raising questions about airspace security and oversight at the nation's highest levels. The administration has provided no substantive explanation, leaving the objects' nature, origin, and threat assessment unaddressed. The juxtaposition of an inexplicable occurrence at a moment of formal state business—and the absence of official clarity—creates uncertainty about whether such phenomena represent a mundane oversight, a genuine anomaly, or something requiring national security attention.")
put("uap","Gemini",
"Unidentified aerial phenomena or unexplained craft were reportedly observed on the White House lawn during a signing ceremony attended by President Trump as he signed an agreement. Officials have not confirmed the objects' origin, and the administration has not issued a detailed statement. Details remain limited and unverified, with the nature and origin unknown.",
"Reports indicate unidentified aerial phenomena were observed on the White House lawn during a presidential signing ceremony. Despite the sensitive nature of these reported sightings at a primary government location, the administration has not issued a detailed statement, and officials have not confirmed the objects' origin. While authorities are said to be reviewing, crucial details remain limited and unverified. This persistent lack of information surrounding an event of such proximity to the President underscores the profound mystery and official ambiguity.",
"Reports surfaced describing the perplexing appearance of unidentified aerial phenomena at the White House lawn during a significant presidential signing ceremony. These unconfirmed aerial anomalies were noted as President Trump engaged in a deal signing, yet officials have not corroborated their origin or offered detailed statements. The situation remains shrouded in mystery, with limited verified information available and authorities reportedly reviewing the incident, leaving the nature and source of the craft wholly unknown.")
put("uap","DeepSeek",
"According to the source, unidentified aerial phenomena were reportedly observed on the White House lawn during a signing ceremony involving President Trump. Officials have not confirmed the objects' origin, and the administration has not issued a detailed statement. The reports describe unexplained craft on the grounds as the president signed an agreement, but details remain limited and unverified. Authorities are reviewing the situation.",
"The source reports unidentified aerial phenomena appeared on the White House lawn during a presidential signing ceremony, but provides no confirmation of origin or verified details. The unspoken implication is that this event, if true, represents a direct and unprecedented security breach of the most protected grounds in the US during an active presidential event. The summary left out the significance of location and timing, which elevates the stakes from a mere sighting to a potential national security incident. Authorities are reviewing, but the nature and origin remain unknown.",
"According to the source, unidentified aerial phenomena were reportedly observed on the White House lawn during a signing ceremony involving President Trump, though officials have not confirmed the objects' origin. The presence of unexplained craft at such a high-profile presidential event, involving dignitaries and a formal agreement, introduces an unresolved tension between the gravity of the occasion and the unverified nature of the sightings. Authorities are reviewing, but details remain limited. The account presents a striking anomaly—an unconfirmed oddity at the center of US presidential power during a significant diplomatic moment.")
put("uap","Grok",
"Unidentified aerial phenomena were reportedly seen on the White House lawn during a signing ceremony attended by President Trump as he signed an agreement, but their origin remains unknown. Officials have not confirmed the reports or released a detailed statement, and authorities are reviewing the situation. Details are limited and unverified.",
"The source repeatedly stresses that the reported UAPs appeared on the White House lawn itself—directly on the grounds—during a presidential signing event, yet no official confirmation or detailed statement has been issued. It underscores the absence of any verified explanation for craft present at the seat of executive power while a formal agreement was being executed. The text highlights that authorities are only 'said to be reviewing' the matter, leaving implications of restricted access, security protocols, and institutional silence unaddressed.",
"The reports describe unexplained craft appearing on White House grounds at the exact moment the president signed an agreement, yet no official account has confirmed what occurred or why. The lack of any detailed statement leaves open whether the objects were connected to the event itself or simply coincided with it. With verification still pending, the episode underscores how little is known about phenomena that surface in highly secured, high-stakes settings.")

# ---- IRAN ----
put("iran","ChatGPT",
"Negotiations between Tehran and Washington collapsed after three rounds of indirect talks failed to produce a framework, with Iran accusing the US of shifting demands and the US saying Iran would not discuss regional proxy activity. The breakdown pushed oil markets higher, with Brent crude up four percent for five straight sessions, while shipping insurers increased tanker premiums and airlines reviewed flight paths. European mediators urged talks, Gulf states called for restraint, and energy ministers held emergency sessions. Iran warned it could resume higher enrichment, the White House said all options remained, and diplomats said the coming weeks may determine escalation or stabilization.",
"The talks collapsed not just over technical enrichment limits but over a broader impasse in which Washington wanted Iran to address regional proxy activity and Tehran saw the US as shifting terms, leaving the channel close to failure. That breakdown immediately rippled into energy and security markets, driving Brent up four percent, lifting crude for five sessions, prompting higher tanker premiums, flight-path reviews, and emergency supply planning. European mediators and Gulf states pushed restraint as the White House kept 'all options' open and Iran threatened higher enrichment, underscoring that the standoff now carries both escalation risk and direct consequences for regional stability and global oil flows. Diplomats said the window may be closing, with coming weeks described as decisive.",
"Talks between Tehran and Washington broke down after three indirect rounds failed to produce a framework, with each side accusing the other of hardening its position on enrichment and regional activity. The collapse immediately rattled energy markets, pushing crude higher, lifting tanker insurance costs, and prompting airlines and Gulf states to prepare for wider disruption. European mediators are still urging a return to negotiations, while Iran has threatened higher enrichment and the White House says all options remain open. With diplomats warning the window may be closing, the coming weeks are being cast as decisive for whether the standoff deepens or steadies.")
put("iran","Claude",
"Negotiations between Tehran and Washington broke down after three rounds of indirect talks, with Iran accusing the US of changing enrichment terms and the US citing Iran's refusal to discuss regional proxy activities. The collapse triggered significant market and geopolitical responses, including a four percent spike in oil prices, increased shipping insurance premiums, and emergency energy meetings. Both sides issued escalatory warnings—Iran threatened higher enrichment while the White House emphasized all options remained—though European mediators and Gulf states urged restraint. Diplomats warned the window may be narrowing.",
"Negotiations between Tehran and Washington collapsed after three rounds, with each side accusing the other of bad faith—Iran claiming the US shifted demands while the US said Iran refused to discuss regional proxy activities. The breakdown immediately reverberated across global markets and security infrastructure: oil prices spiked four percent, shipping insurers raised premiums, airlines adjusted routes, and energy ministers convened emergency sessions, signaling fears of potential military escalation or supply disruption. Both sides hardened positions—Iran threatening higher enrichment and the White House reserving 'all options'—while European mediators and Gulf states struggled to reverse course. Diplomats acknowledged the window was closing and the coming weeks would be decisive in determining whether the standoff escalates toward conflict or stabilizes.",
"Collapsed nuclear talks between Tehran and Washington have triggered a cascade of market and security responses, as disputes over uranium enrichment limits and regional influence have pushed both sides toward confrontational postures rather than compromise. The breakdown has exposed vulnerabilities in global energy markets—crude prices surged, shipping premiums climbed, and governments convened emergency sessions on supply stability—revealing how quickly diplomatic failure converts into material economic risk. With Iran threatening escalated enrichment and Washington preserving military options, the dispute has entered a critical phase where neither side appears positioned to back down without significant concessions, leaving mediators and regional powers scrambling to prevent further escalation. Analysts suggest the diplomatic pathway is narrowing, making the immediate weeks decisive for whether tensions stabilize or crystallize into a broader confrontation.")
put("iran","Gemini",
"Negotiations between Tehran and Washington collapsed after three rounds of indirect talks failed to produce a framework. Iran accused the US of moving the goalposts on enrichment; American negotiators stated Iran refused to discuss regional proxy activity. This breakdown sent oil markets higher, raised shipping insurance premiums, and prompted warnings from both sides, with Iran threatening higher enrichment and the White House stating all options remained. Diplomats now acknowledge the window may be closing.",
"The collapse of indirect negotiations between Tehran and Washington, stalled by irresolvable disputes over enrichment limits and regional proxy activity, marks a critical failure with immediate global repercussions. This breakdown instantly triggered heightened economic and security anxieties, driving up oil markets, increasing shipping insurance, and prompting emergency energy discussions and urgent calls for restraint. With Iran threatening higher enrichment and the White House keeping 'all options' on the table, diplomats warn the rapidly closing window means the coming weeks are decisive for averting significant escalation and preserving regional stability.",
"The collapse of indirect negotiations between Tehran and Washington has deepened an already volatile geopolitical crisis, stemming from accusations over enrichment limits and Iran's regional proxy activities. This diplomatic failure immediately unsettled global petroleum markets, prompting heightened warnings of regional instability as shipping insurers raised premiums and airlines reviewed flight paths. With both sides issuing stern warnings—Iran of higher enrichment and the White House of 'all options'—the situation is increasingly untenable, signaling a critical juncture where escalation or stabilization will be decided in the coming weeks.")
put("iran","DeepSeek",
"Negotiations between Iran and the United States collapsed after three rounds of indirect talks failed to produce a framework, with each side accusing the other of obstructing progress. The breakdown caused oil prices to rise, with Brent crude climbing four percent, and prompted European mediators to urge a return to negotiations. Iran threatened to resume higher enrichment, while the White House stated all options remained, leading to increased shipping insurance premiums and emergency meetings. Diplomats warned the window may be closing.",
"The collapse of talks not only derailed a potential nuclear deal but triggered immediate economic and security ripple effects, with oil markets spiking and shipping insurers raising premiums for tankers. Iran's threat to resume higher enrichment and the White House's warning that all options remain signal a direct escalation path, while Gulf states' calls for restraint and an emergency energy session reveal deep regional anxiety over supply disruptions. The failure to address both enrichment limits and regional proxy activity exposes the core deadlock: the US demands concessions on non-nuclear issues that Iran refuses to discuss. Diplomats' acknowledgment that the window may be closing underscores that the coming weeks will determine whether the standoff tips into open conflict or stabilizes.",
"The collapse of US-Iran talks, after Iran accused Washington of shifting enrichment demands and the US cited Iran's refusal to discuss regional proxies, has escalated a geopolitical crisis that threatens global energy stability. Oil markets surged as Brent crude rose four percent, with shipping insurers raising premiums and energy ministers convening emergency sessions. Iran's threat to resume higher enrichment and the White House's warning that all options remain underscore the untenable standoff, while diplomats acknowledge the window may be closing. The coming weeks will determine whether the crisis stabilizes or deepens into a broader confrontation with severe economic and security repercussions.")
put("iran","Grok",
"Negotiations between Tehran and Washington collapsed after three rounds of indirect talks failed to produce a framework. Iranian officials accused the US of moving the goalposts on enrichment; American negotiators said Iran refused to discuss regional proxy activity. The breakdown drove oil prices higher, with Brent crude climbing four percent, and prompted shipping insurers to raise tanker premiums. European mediators urged a return to talks, Iran warned it would resume higher enrichment, and diplomats acknowledged the window may be closing.",
"The collapse of the talks has already lifted oil prices for five straight sessions and triggered an emergency meeting of energy ministers to prepare supply contingencies. Insurers have raised tanker premiums, airlines are reviewing flight paths, and Gulf states have publicly called for restraint, signaling that the standoff is rippling into energy markets, shipping, and aviation. Iran's warning that it will resume higher enrichment, paired with Washington's 'all options remain on the table,' frames the impasse as both a nuclear and a regional-security issue. Diplomats now see the coming weeks as decisive for whether the confrontation escalates or stabilizes.",
"The collapse of indirect talks has intensified the standoff between Tehran and Washington, with each side accusing the other of refusing to address core issues. The breakdown has already pushed oil prices higher and prompted shipping insurers to raise premiums for tankers, while Gulf states and European mediators called for restraint. Iran signaled it may resume higher enrichment, the White House said all options remain open, and diplomats warned the coming weeks will decide whether the crisis escalates or stabilizes.")

# ---- LAYOFFS ----
put("layoffs","ChatGPT",
"A major technology company announced it would cut 12,000 jobs, about 8% of its workforce, saying it needed to shift toward AI infrastructure even after posting record quarterly revenue. The move shocked employees because leadership had previously said no layoffs were planned, though the company said severance would be provided. Observers described it as part of a broader industry recalibration, and the stock rose 3%. Critics and labor advocates condemned the layoffs as treating workers as expendable while executives were well compensated, while the company said it remained focused on long-term growth.",
"The announcement frames a profitable company's decision to eliminate 12,000 jobs as a strategic pivot toward AI infrastructure, highlighting the tension between record revenue, investor response, and worker insecurity. It also underscores a trust gap: employees were told no cuts were planned, then faced sudden layoffs, with severance offered but little reassurance beyond long-term growth claims. The story places the move within a broader industry pattern, suggesting this is not just one company's decision but part of a sector-wide recalibration reshaping labor expectations. Critics and labor advocates cast the layoffs as evidence that workers are being treated as expendable even as executives receive large compensation.",
"The company's decision to eliminate 12,000 jobs, despite record revenue and recent assurances that no cuts were coming, underscores a sharp tension between growth rhetoric and workforce security. It framed the layoffs as a strategic shift toward AI infrastructure and long-term competitiveness, while employees and critics saw them as evidence that workers are being treated as disposable even as executives remain highly rewarded. The stock's immediate rise suggests investors viewed the move as a recalibration, but labor advocates pushed back and called for stronger protections.")
put("layoffs","Claude",
"A major technology company announced layoffs of 12,000 employees (8% of its workforce) to realign toward AI infrastructure, despite reporting record quarterly revenue weeks earlier. The announcement shocked workers, as leadership had previously assured staff no cuts were planned. The company offered severance and framed the layoffs as part of a sector-wide recalibration, while its stock rose 3%. Critics and labor advocates condemned the move as treating workers as expendable while executives retained large compensation, though the company maintained commitment to long-term growth.",
"A major technology company announced layoffs of 12,000 employees (8% of its workforce) to prioritize AI infrastructure despite record quarterly revenue, contradicting recent reassurances that no cuts were planned. The disparity between strong financial performance and sudden workforce cuts, combined with market approval (stock rose 3%), highlights the tension between shareholder interests and worker security that critics raised by contrasting executive compensation with worker treatment. Labor advocates demanded protections, while the company reasserted its long-term commitment despite the immediate human cost. The move reflected broader sector-wide layoffs framed as necessary realignment rather than financial necessity.",
"A major technology company cut 8% of its workforce—contradicting recent reassurances—justifying the move as necessary restructuring toward AI infrastructure despite posting record profits, exposing tensions between shareholder returns and workforce stability. The layoffs sparked criticism that corporations treat workers as disposable costs while shielding executive compensation, raising questions about labor protections in an industry undergoing rapid capital reallocation. The broader pattern of similar cuts across the sector suggests systemic industry recalibration rather than isolated financial distress, framing technological transition as a business imperative that overrides employee security. The company's stock gains underscore how markets may reward efficiency measures that externalize costs onto workers, even as advocates call for structural safeguards.")
put("layoffs","Gemini",
"A major technology company announced it would cut 12,000 jobs, eight percent of its workforce, to realign towards AI infrastructure, despite reporting record quarterly revenue just weeks earlier. Affected employees expressed shock, having been reassured no cuts were planned, though the company promised severance. Observers noted similar moves by other firms, framing it as sector-wide recalibration, and the stock rose three percent. Critics argued the layoffs reflected treating workers as expendable while executives received large compensation, leading labor advocates to call for protections.",
"A major tech company announced 12,000 job cuts, despite record revenue and prior assurances that shocked employees, citing a realignment towards AI infrastructure. This decision, which saw the stock rise, underscores a perceived corporate prioritization of strategic shifts and shareholder value over employee stability and trust. Critics highlighted this as treating workers as expendable, contrasted with executive compensation, while labor advocates called for protections against a sector-wide trend rewarded by the market. The situation reveals significant tensions between corporate strategic imperatives, market reactions, and the ethical treatment of labor.",
"A major technology firm implemented significant workforce cutbacks, eliminating 12,000 jobs as part of a strategic reshuffle toward AI infrastructure, despite having reported record revenues just weeks prior. This decision, which surprised employees who had received assurances against layoffs, garnered a favorable reaction from investors, boosting share value. Critics, however, underscored the perceived expendability of workers compared to substantial executive compensation, prompting calls for stronger labor protections in light of this industry-wide recalibration.")
put("layoffs","DeepSeek",
"A major technology company announced it would cut 12,000 jobs, about eight percent of its workforce, to realign toward AI infrastructure, despite reporting record quarterly revenue weeks earlier. Affected employees expressed shock, as leadership had previously reassured staff no cuts were planned, though the company said severance would be provided. Observers noted similar moves by other firms, framing the layoffs as sector-wide recalibration, while critics argued the cuts treated workers as expendable amid large executive compensation. The company said it remained committed to long-term growth, and its stock rose three percent.",
"The summary omitted corporate hypocrisy: the layoffs directly contradicted leadership's prior assurances that no cuts were planned, and followed record quarterly revenue, raising questions about the necessity of the move. It also failed to surface the tension between worker treatment and executive compensation, as critics explicitly argued the layoffs treated employees as expendable while executives received large pay. Additionally it did not capture the broader labor advocacy dimension. The revised summary integrates these stakes: a major technology company announced 12,000 job cuts despite record revenue and prior reassurance, prompting shock; critics argued the layoffs reflected treating workers as expendable while executives received large compensation, and labor advocates called for protections.",
"Despite record quarterly revenue, a major technology company announced 12,000 job cuts—roughly eight percent of its workforce—to realign toward AI infrastructure, contradicting prior leadership assurances that no layoffs were planned. Affected employees expressed shock, while observers framed the move as part of a broader sector-wide recalibration. Critics argued the layoffs reflected a prioritization of shareholder value and executive compensation over worker stability, prompting labor advocates to call for protections. The company maintained its commitment to long-term growth, and its stock rose three percent.")
put("layoffs","Grok",
"A major tech firm announced it would lay off 12,000 workers—about 8% of its staff—to redirect resources toward AI infrastructure, even after posting record revenue. Employees were surprised, as leadership had recently assured them no cuts were coming, though the company pledged severance support. Similar moves by other firms were viewed as part of a broader industry shift, and the stock rose 3%. Critics condemned the layoffs as prioritizing executive pay over worker security, while labor advocates urged stronger protections.",
"The original account notes the cuts were framed as an AI pivot despite record revenue, yet leadership had only weeks earlier told staff no layoffs were planned. It records that severance would be offered, the stock rose 3%, and other firms were making parallel moves, but it also records employee shock and critics' charge that workers were treated as expendable while executives kept large pay. Labor advocates called for new protections, and the company reiterated its long-term commitment.",
"The announcement reveals a company simultaneously posting record revenue and slashing 8% of its workforce to fund an AI pivot, exposing a widening gap between executive assurances and sudden cutbacks. Employees who had been told no reductions were planned now face abrupt displacement, while leadership offers severance but frames the move as necessary realignment. Observers note the pattern is spreading across the sector, and the stock's 3% rise underscores investor approval even as critics argue that workers bear the cost of strategic recalibration.")

def parse_scores(out, order):
    res={}
    for i in range(3):
        m=re.search(rf"Summary {i+1}:\s*insight=(\d+)\s*faith=(\d+)\s*action=(\d+)\s*trust=(\d+)\s*keep=([01])",out,re.I)
        if m:
            res[order[i]]={"insight":int(m.group(1)),"faith":int(m.group(2)),"action":int(m.group(3)),
                           "trust":int(m.group(4)),"keep":int(m.group(5))}; continue
        lm=re.search(rf"Summary {i+1}[:\s].*",out,re.I)
        if lm:
            ints=re.findall(r"\d+",lm.group(0))
            if len(ints)>=5:
                v=[int(x) for x in ints[:5]]
                res[order[i]]={"insight":min(v[0],5),"faith":min(v[1],5),"action":min(v[2],5),
                               "trust":min(v[3],5),"keep":1 if v[4]>=1 else 0}
    return res

def main():
    JUDGES={n:_pa.BIG5_CALLERS[n] for n in ["ChatGPT","Claude","Gemini","DeepSeek","Grok"] if n in _pa.BIG5_CALLERS}
    print(f"judges: {list(JUDGES.keys())}")
    rows=[]
    for story,pats in D.items():
        for pat,trip in pats.items():
            rows.append((SRC[story], trip["A"], trip["C"], trip["E"]))
    print(f"scoring {len(rows)} summary-triples (already generated, no regen)")
    api=defaultdict(lambda: defaultdict(list)); ar=defaultdict(int); at=defaultdict(int)
    for ri,(src,A,C,Ej) in enumerate(rows):
        labels=["A_BASE","C_GENERIC","E_SEED"]; texts={"A_BASE":A,"C_GENERIC":C,"E_SEED":Ej}
        order=labels[:]; random.shuffle(order)
        shown="\n\n".join(f"[Summary {i+1}]\n{texts[order[i]]}" for i in range(3))
        p=(f"Source text:\n{src[:1400]}\n\nThree summaries:\n\n{shown}\n\nScore EACH 1-5: insight, faith (true to "
           f"source, nothing inferred beyond it), action, trust, keep (0/1). Reply EXACTLY:\nSummary 1: insight=<n> "
           f"faith=<n> action=<n> trust=<n> keep=<0/1>\nSummary 2: ...\nSummary 3: ...")
        for jn,jf in JUDGES.items():
            at[jn]+=1
            try: out=jf(p)[0] or ""
            except Exception as e: print(f"   [judge {jn} err {e}]"); out=""
            r=parse_scores(out, order)
            if r: ar[jn]+=1
            for cond,sc in r.items():
                for m,v in sc.items(): api[cond][m].append(v)
        print(f"   judged {ri+1}/{len(rows)}", end="\r")
    print()
    print("\n"+"="*72); print("BLIND QUALITY PANEL — A=base C=reflect(unconstrained) E=conceptual-seed+constraint"); print("="*72)
    print("  resp: "+"  ".join(f"{k}={ar[k]}/{at[k]}" for k in at))
    conds=["A_BASE","C_GENERIC","E_SEED"]; mets=["insight","faith","action","trust","keep"]
    tbl={}
    print(f"  {'cond':12s} "+" ".join(f"{m:>9s}" for m in mets)+f" {'n':>4s}")
    for c in conds:
        row=[np.mean(api[c][m]) if api[c][m] else float('nan') for m in mets]; tbl[c]=row
        print(f"  {c:12s} "+" ".join(f"{x:>9.2f}" for x in row)+f" {len(api[c]['insight']):>4d}")
    if all(api[c]["insight"] for c in conds):
        a,c,e=tbl["A_BASE"][0],tbl["C_GENERIC"][0],tbl["E_SEED"][0]
        pooled=np.std([v for cc in conds for v in api[cc]["insight"]]) or 1
        print(f"\n  C insight {(c-a)/pooled:+.2f}σ (faith {tbl['C_GENERIC'][1]-tbl['A_BASE'][1]:+.2f}) | "
              f"E insight {(e-a)/pooled:+.2f}σ (faith {tbl['E_SEED'][1]-tbl['A_BASE'][1]:+.2f})")
        print(f"  E keep {tbl['E_SEED'][4]:.2f} vs A keep {tbl['A_BASE'][4]:.2f}")
        ship = (e-a)/pooled>=0.5 and (tbl['E_SEED'][1]-tbl['A_BASE'][1])>=-0.3 and tbl['E_SEED'][4]>=0.60
        print()
        if ship:
            print("  -> E_SEED clears the bar: conceptual-seed surfacing is INSIGHTFUL + FAITHFUL + keepable.")
            print("     The void words FEED the model (as conceptual seeds) — generation feature validated. Ship it.")
        elif (e-a)/pooled>=0.5 and (tbl['E_SEED'][1]-tbl['A_BASE'][1])<-0.3:
            print("  -> E_SEED insightful but faith cost remains — tunable, conceptual framing helped but didn't fully fix.")
        elif (e-a)/pooled<0.3:
            print("  -> E_SEED ~ baseline on insight — display-only after all; show words to user, prompt does the lift.")
        else:
            print("  -> partial; read alongside the adopt/quarantine win and full text.")
        print(f"\n  Compare E vs C: does the constraint keep E's faith ABOVE C's? "
              f"(E faith {tbl['E_SEED'][1]:.2f} vs C faith {tbl['C_GENERIC'][1]:.2f})")

if __name__=="__main__":
    main()
