#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""sitemap_gen.py -- regenerate docs/sitemap.xml from what is actually in docs/.

VERSION = "sitemap_gen v1.1 2026-07-10"

The sitemap is a curated SEO surface, not a directory dump. Declared rules:
  INCLUDE  docs/*.html and docs/blog/*.html, plus / if docs/index.* exists
           Jekyll markdown pages: front-mattered docs/*.md and
           blog/*.md; permalink honored, else the filename slug
  EXCLUDE  Jekyll internals (any path segment starting with _)
           backups / versioned duplicates: *.stale*, *.bak*, *.v2.html
           site-verification stubs: google*.html
           redirect stubs: files under 2000 bytes containing an
           http-equiv refresh or the phrase 'has moved'
  URL      extensionless (house pattern: /summary-plus, /vf-idf);
           index.* -> /
  lastmod  git last-commit date for the file; mtime fallback if untracked
  order    alphabetical by URL, so identical trees emit identical bytes

Safety: refuses to write fewer than 10 entries (a broken scan must not
nuke the live sitemap), and moves any existing sitemap.xml that this
generator did not write to ~/eigentrace_scratch/ before replacing it.

Prints one report line per decision; judge the run by its own report.
"""
VERSION = "sitemap_gen v1.1 2026-07-10"

import argparse
import glob
import hashlib
import os
import re
import subprocess
import sys
from datetime import datetime

MARK = "generated by sitemap_gen"

ap = argparse.ArgumentParser()
ap.add_argument("--docs", default="docs")
ap.add_argument("--base", default="https://eigentrace.ai")
ap.add_argument("--out", default=None, help="default: {docs}/sitemap.xml")
a = ap.parse_args()
out = a.out or os.path.join(a.docs, "sitemap.xml")


def lastmod(path):
    try:
        d = subprocess.run(["git", "log", "-1", "--format=%cs", "--", path],
                           capture_output=True, text=True).stdout.strip()
        if re.fullmatch(r"\d{4}-\d{2}-\d{2}", d):
            return d
    except Exception:
        pass
    return datetime.fromtimestamp(os.path.getmtime(path)).strftime("%Y-%m-%d")


def excluded(path):
    low = os.path.basename(path).lower()
    if ".stale" in low or ".bak" in low or low.endswith(".v2.html"):
        return "backup / versioned duplicate"
    if low.startswith("google") and low.endswith(".html"):
        return "site-verification stub"
    try:
        if os.path.getsize(path) < 2000:
            s = open(path, encoding="utf-8", errors="replace").read().lower()
            if 'http-equiv="refresh"' in s or "has moved" in s:
                return "redirect stub"
    except Exception:
        pass
    return None


entries, report = [], []

home = next((n for n in ("index.html", "index.md", "index.markdown")
             if os.path.exists(os.path.join(a.docs, n))), None)
if home:
    p = os.path.join(a.docs, home)
    entries.append((a.base + "/", lastmod(p)))
    report.append(("INCLUDE", "/", lastmod(p), "homepage (%s)" % home))
else:
    report.append(("NOTE", "/", "", "no index.* in docs -- homepage entry "
                   "skipped; if Jekyll builds / from elsewhere, say so and "
                   "the rule extends"))

for pat in ("*.html", "blog/*.html"):
    for p in sorted(glob.glob(os.path.join(a.docs, pat))):
        rel = os.path.relpath(p, a.docs).replace(os.sep, "/")
        if any(seg.startswith("_") for seg in rel.split("/")):
            continue
        if rel in ("index.html",):
            continue                       # homepage handled above
        why = excluded(p)
        if why:
            report.append(("EXCLUDE", rel, "", why))
            continue
        slug = "/" + re.sub(r"\.html$", "", rel)
        entries.append((a.base + slug, lastmod(p)))
        report.append(("INCLUDE", slug, lastmod(p), ""))

# Jekyll markdown pages: front matter is what makes Jekyll build them
for pat in ("*.md", "blog/*.md"):
    for p in sorted(glob.glob(os.path.join(a.docs, pat))):
        rel = os.path.relpath(p, a.docs).replace(os.sep, "/")
        base = os.path.basename(rel).lower()
        if base.startswith("index.") or base == "readme.md":
            continue
        if any(seg.startswith("_") for seg in rel.split("/")):
            continue
        try:
            head = open(p, encoding="utf-8", errors="replace").read(4000)
        except Exception:
            continue
        body = head.lstrip()
        if not body.startswith("---"):
            report.append(("EXCLUDE", rel, "",
                           "md without front matter -- not a Jekyll page"))
            continue
        fm = body[3:].split("\n---", 1)[0]
        m = re.search(r"^permalink:\s*(\S+)", fm, re.M)
        slug = (m.group(1).rstrip("/") if m
                else "/" + re.sub(r"\.(md|markdown)$", "", rel))
        if not slug.startswith("/"):
            slug = "/" + slug
        entries.append((a.base + slug, lastmod(p)))
        report.append(("INCLUDE", slug, lastmod(p),
                       "md page" + (", permalink" if m else "")))

entries = sorted(set(entries))
for kind, slug, lm, note in report:
    print("%-8s %-58s %-10s %s" % (kind, slug, lm, note))
print("-- %d URLs" % len(entries))

if len(entries) < 10:
    sys.exit("STOP: only %d entries -- scan looks wrong, sitemap NOT written"
             % len(entries))

xml = ['<?xml version="1.0" encoding="UTF-8"?>',
       "<!-- generated by %s -- deterministic; edit the generator, "
       "not this file -->" % VERSION,
       '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
for url, lm in entries:
    xml.append("  <url><loc>%s</loc><lastmod>%s</lastmod></url>" % (url, lm))
xml.append("</urlset>")
body = "\n".join(xml) + "\n"

if os.path.exists(out):
    old = open(out, encoding="utf-8", errors="replace").read()
    if MARK not in old:
        scratch = os.path.expanduser("~/eigentrace_scratch")
        os.makedirs(scratch, exist_ok=True)
        bak = os.path.join(scratch, "sitemap.xml.pre_gen")
        if not os.path.exists(bak):
            open(bak, "w", encoding="utf-8").write(old)
            print("foreign sitemap preserved -> %s" % bak)

open(out, "w", encoding="utf-8").write(body)
print("SITEMAP -> %s (%d bytes, %d urls, sha %s)"
      % (out, len(body), len(entries),
         hashlib.sha256(body.encode()).hexdigest()[:12]))
