#!/usr/bin/env python3
"""
soul_updater.py — Self-updating soul.md from live eigenvalues
=============================================================
Reads last 24h of segments, computes rolling averages,
and appends a Live Calibration section to soul.md.

This is the feedback loop: the instrument measures the models,
then the measurements condition the host model's next output.
"""

import json, glob, os
from datetime import datetime, timedelta

SEGMENT_DIR = "/home/remvelchio/eigentrace/tmp/segments"
SOUL_PATH = "/mnt/c/Users/M4ISI/eigentrace/docs/soul.md"
SOUL_MARKER = "## Live Calibration"

def load_recent_segments(hours=24):
    cutoff = datetime.utcnow() - timedelta(hours=hours)
    segments = []
    for f in glob.glob(os.path.join(SEGMENT_DIR, "*_segment.json")):
        try:
            d = json.load(open(f))
            ts = datetime.strptime(d["timestamp"], "%Y%m%d_%H%M%S")
            if ts > cutoff:
                segments.append(d)
        except:
            continue
    return segments

def compute_calibration(segments):
    if not segments:
        return None

    densities = []
    vix_scores = {m: [] for m in ["ChatGPT", "Claude", "Gemini", "DeepSeek", "Grok"]}
    verb_drifts = []
    entity_retentions = []
    absent_ratios = []
    hedge_counts = []
    categories = {}

    for s in segments:
        attr = s.get("attribution", {})

        if "consensus_density" in attr:
            densities.append(attr["consensus_density"])

        mvix = attr.get("model_vix", {})
        for m, v in mvix.items():
            if m in vix_scores:
                vix_scores[m].append(v)

        comp = attr.get("compression", {})
        if "verb_downgrade" in comp:
            verb_drifts.append(comp["verb_downgrade"])
        if "entity_retention" in comp:
            entity_retentions.append(comp["entity_retention"])

        ab = comp.get("attribution_buffer", {})
        if isinstance(ab, dict) and "total" in ab:
            hedge_counts.append(ab["total"])

        sv = attr.get("source_void", {})
        if "absent_ratio" in sv:
            absent_ratios.append(sv["absent_ratio"])

        cat = attr.get("category", "unknown")
        categories[cat] = categories.get(cat, 0) + 1

    def avg(lst):
        return round(sum(lst) / len(lst), 3) if lst else 0

    model_avg_vix = {m: avg(scores) for m, scores in vix_scores.items() if scores}
    outlier = max(model_avg_vix, key=model_avg_vix.get) if model_avg_vix else "unknown"

    return {
        "stories": len(segments),
        "density": avg(densities),
        "verb_drift": avg(verb_drifts),
        "entity_retention": avg(entity_retentions),
        "absent_ratio": avg(absent_ratios),
        "hedges": sum(hedge_counts),
        "model_vix": model_avg_vix,
        "outlier": outlier,
        "top_categories": dict(sorted(categories.items(), key=lambda x: -x[1])[:5]),
        "updated": datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
    }

def update_soul(cal):
    if not cal:
        return

    block = f"""
{SOUL_MARKER}
_Auto-generated by soul_updater.py — do not edit manually._
_Last updated: {cal['updated']}_

### Rolling 24h Instrument Readings ({cal['stories']} stories)

| Metric | Value | Interpretation |
|--------|-------|----------------|
| Consensus Density | {cal['density']} | {'LOCKSTEP — models highly aligned' if cal['density'] > 0.9 else 'DIVERGENT — models disagree' if cal['density'] < 0.8 else 'Normal consensus'} |
| Mean Absent Ratio | {cal['absent_ratio']} | {cal['absent_ratio']*100:.0f}% of source content dropped by models |
| Verb Drift | {cal['verb_drift']} | {'Significant softening detected' if cal['verb_drift'] > 0.1 else 'Minimal verb softening'} |
| Entity Retention | {cal['entity_retention']} | {cal['entity_retention']*100:.0f}% of named entities preserved |
| Total Hedges (24h) | {cal['hedges']} | Attribution buffer insertions |
| VIX Outlier | {cal['outlier']} | Most divergent model in window |

### Per-Model VIX (24h average)
{chr(10).join(f'- **{m}**: {v}' for m, v in sorted(cal['model_vix'].items(), key=lambda x: -x[1]))}

### Category Distribution
{chr(10).join(f'- {cat}: {n} stories' for cat, n in cal['top_categories'].items())}

### Calibration Guidance
{'⚠️ Absent ratio above 0.7 — models are dropping significant content. Weight void words heavily in dream state.' if cal['absent_ratio'] > 0.7 else '✓ Absent ratio within normal range.' }
{'⚠️ Verb drift above 0.1 — models are softening language. Check for hedging in sensitive topics.' if cal['verb_drift'] > 0.1 else '✓ Verb drift within normal range.'}
{'⚠️ Consensus density above 0.92 — possible LOCKSTEP. Models may be converging on safe framing.' if cal['density'] > 0.92 else '✓ Consensus density normal.'}
"""

    # Read existing soul.md
    with open(SOUL_PATH, "r") as f:
        content = f.read()

    # Remove old calibration section if present
    if SOUL_MARKER in content:
        content = content[:content.index(SOUL_MARKER)].rstrip()

    # Append new calibration
    content = content + "\n" + block

    with open(SOUL_PATH, "w") as f:
        f.write(content)

    print(f"Soul updated: {cal['stories']} stories, density={cal['density']}, "
          f"absent={cal['absent_ratio']}, drift={cal['verb_drift']}, outlier={cal['outlier']}")

if __name__ == "__main__":
    segments = load_recent_segments(hours=24)
    cal = compute_calibration(segments)
    update_soul(cal)
